Algoritmo "Antecessor"
// Disciplina   :Lógica de Programação
// Professor   : Obama
// Descrição   : Solicitar um número antecessor
// Autor(a)    : Dudu
// Data atual  : 21/03/2022
Var
// Seção de Declarações das variáveis 
numero, antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Bom dia!")
escreval("Digite um número:")
leia(numero)
antecessor <- numero - 1
escreval("O número antecessor é:",antecessor)

Fimalgoritmo