Algoritmo "LacoDeRepeticao"
// Disciplina  : [Lógica de Programação com JavaScripts]
// Professor   : Obama
// Descrição   : Aprendendo laços
// Autor(a)    : Dudu
// Data atual  : 28/03/2022
Var
   // Seção de Declarações das variáveis
   cont: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto cont < 12 faca
      Escreval("Dudu")
      cont <- + 1
   fimenquanto
Fimalgoritmo