Algoritmo "6a"
// Disciplina  : Lógica de Programação
// Professor   : Obama
// Descrição   : Calcula o sucessor
// Autor(a)    : Dudu
// Data atual  : 21/03/2022
Var
// Seção de Declarações das variáveis 
valorF: real
valorC: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Graus Celsius: ")
leia(valorC)
valorF <- (valorC * 9/5) + 32
escreval(valorC,"ºC =",valorF,"ºF")

Fimalgoritmo