Algoritmo "ex12"
// Disciplina  : Lógica de Programação
// Professor   : Obama
// Descrição   : Calcula o sucessor
// Autor(a)    : Dudu
// Data atual  : 21/03/2022
Var
// Seção de Declarações das variáveis 
tempF: real
tempC: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Graus Fahrenheit: ")
leia(tempF)
tempC <- (tempF - 32) * 5/9
Escreval(tempF,"ºF =", tempC,"ºC")

Fimalgoritmo